/**
 * Nano Banana integration — Gemini-powered image generation.
 *
 * Uses the Google Generative AI (Gemini) API to generate and edit images
 * for campaign receipts, PFP enhancements, and promotional visuals.
 */

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta'
const MODEL = 'gemini-2.0-flash-exp'

export interface NanoBananaGenerateOptions {
  /** Text prompt describing the desired image */
  prompt: string
  /** Optional reference image as base64 data URI */
  referenceImage?: string
  /** Desired aspect ratio (default: '1:1') */
  aspectRatio?: '1:1' | '16:9' | '9:16' | '4:3'
}

export interface NanoBananaResult {
  /** Generated image as base64 data URI */
  imageDataUri: string
  /** Text response from the model, if any */
  textResponse?: string
}

function getApiKey(): string {
  const key = process.env.GEMINI_API_KEY
  if (!key) {
    throw new Error('GEMINI_API_KEY environment variable is not set')
  }
  return key
}

/**
 * Generate an image using Nano Banana (Gemini image generation).
 */
export async function generateImage(
  options: NanoBananaGenerateOptions
): Promise<NanoBananaResult> {
  const apiKey = getApiKey()

  const parts: Array<Record<string, unknown>> = []

  // Add reference image if provided
  if (options.referenceImage) {
    const [header, base64Data] = options.referenceImage.split(',')
    const mimeType = header?.match(/data:(.*?);/)?.[1] ?? 'image/png'
    parts.push({
      inlineData: {
        mimeType,
        data: base64Data,
      },
    })
  }

  // Add text prompt
  parts.push({ text: options.prompt })

  const requestBody = {
    contents: [{ parts }],
    generationConfig: {
      responseModalities: ['TEXT', 'IMAGE'],
    },
  }

  const res = await fetch(
    `${GEMINI_API_BASE}/models/${MODEL}:generateContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(requestBody),
    }
  )

  if (!res.ok) {
    const errorBody = await res.text()
    throw new Error(`Gemini API error (${res.status}): ${errorBody}`)
  }

  const data = await res.json()
  const candidate = data.candidates?.[0]
  if (!candidate) {
    throw new Error('No candidates returned from Gemini API')
  }

  let imageDataUri = ''
  let textResponse = ''

  for (const part of candidate.content?.parts ?? []) {
    if (part.inlineData) {
      const mime = part.inlineData.mimeType ?? 'image/png'
      imageDataUri = `data:${mime};base64,${part.inlineData.data}`
    } else if (part.text) {
      textResponse += part.text
    }
  }

  if (!imageDataUri) {
    throw new Error('No image was generated by the model')
  }

  return { imageDataUri, textResponse: textResponse || undefined }
}

/**
 * Generate a campaign banner image for a drop.
 */
export async function generateCampaignBanner(
  campaignTitle: string,
  campaignType: 'high_tip_drop' | 'cause_drop',
  description?: string
): Promise<NanoBananaResult> {
  const typeLabel =
    campaignType === 'high_tip_drop' ? 'High-Tip Drop' : 'Cause Drop'

  const prompt = [
    `Create a vibrant, celebratory social media banner image for a "${typeLabel}" campaign called "${campaignTitle}".`,
    description ? `Campaign description: ${description}.` : '',
    'Style: modern, clean, with green accent colors (#4ade80). No text overlay needed.',
    'The image should feel uplifting and community-oriented.',
  ]
    .filter(Boolean)
    .join(' ')

  return generateImage({ prompt, aspectRatio: '16:9' })
}

/**
 * Enhance a PFP image with stylistic flair using Nano Banana.
 */
export async function enhancePfpImage(
  imageDataUri: string,
  style?: string
): Promise<NanoBananaResult> {
  const prompt = style
    ? `Enhance this profile picture with a ${style} style. Keep the subject recognizable.`
    : 'Enhance this profile picture to look more vibrant and polished while keeping the subject clearly recognizable.'

  return generateImage({ prompt, referenceImage: imageDataUri })
}
